### ISSUE TITLE
CPAN RT Tickets

### ISSUE THREAD

**Issue by eserte** [dacav/PFT#3] opened 2016-07-19 22:21 UTC
Are you aware of the bugs reported at RT?
https://rt.cpan.org/Dist/Display.html?Name=PFT

**Comment by dacav** [comment] 2016-09-20 11:19
Hello @eserte. Sorry for the late answer.
Yes, I'm aware of it.
It requires a bit of time and patience to find a solution.
The bug is btw caused by a situation which is not common in the use case, that is a system without encoding setted.
I'll investigate when I'll have time.
Thanks for the report :)

**Comment by dacav** [comment] 2018-01-09 10:38
By the way, it is now patched. I'm closing this issue.

**Closed by dacav** 2018-01-09 10:38 UTC
